spring.application.name=Miniproyecto_TiendaWebExpress

# ============================================================
# CONFIGURACIÓN DE POSTGRESQL
# ============================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/tienda_web_express
spring.datasource.username=postgres
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================================
# CONFIGURACIÓN JPA/HIBERNATE
# ============================================================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# ============================================================
# PUERTO DE LA APLICACIÓN
# ============================================================

server.port=8080

# ============================================================
# LOGGING
# ============================================================

logging.level.root=INFO
logging.level.com.tienda=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# ============================================================
# THYMELEAF
# ============================================================

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html